MCU_SERIES = RZA2M
MCU_NUMBER = RR5F565NEDDLI
LD_FILES = boards/GR_MANGO/GR_MANGO_DD.ld
START_FILE = rza2m/startup_rza2m.S

# MicroPython settings
MICROPY_VFS_LFS2 = 1
MICROPY_PY_LWIP=1
MICROPY_PY_USSL=1 
MICROPY_SSL_MBEDTLS=1
MICROPY_PY_ESP=1
MICROPY_PY_LVGL = 1
