MCU_SERIES = RX65N
MCU_NUMBER = RR5F565NEDDLI
LD_FILES = boards/GR_ROSE_DD/gr_rose_dd.ld
START_FILE = rx65n/startup_rx65n.S

# MicroPython settings
MICROPY_VFS_LFS2 = 1
MICROPY_PY_LWIP=1
MICROPY_PY_USSL=1 
MICROPY_SSL_MBEDTLS=1
MICROPY_PY_ESP8266=1
MICROPY_PY_LVGL = 0
