MCU_SERIES = RX63N
MCU_NUMBER = RR5F5631FDDFP
LD_FILES = boards/GR_CITRUS_DD/gr_citrus_dd.ld
START_FILE = rx63n/startup_rx63n.S

# MicroPython settings
MICROPY_VFS_FAT = 1
MICROPY_PY_USSL=1
MICROPY_SSL_MBEDTLS=1
MICROPY_PY_ESP8266=1
