dir ..\..\py\makeqstrdefs.py
dir ..\..\py\mpstate.c
dir ..\..\py\malloc.c
dir ..\..\py\gc.c
dir ..\..\py\pystack.c
dir ..\..\py\qstr.c
dir ..\..\py\vstr.c
dir ..\..\py\mpprint.c
dir ..\..\py\unicode.c
dir ..\..\py\mpz.c
dir ..\..\py\reader.c
dir ..\..\py\lexer.c
dir ..\..\py\parse.c
dir ..\..\py\scope.c
dir ..\..\py\compile.c
dir ..\..\py\emitcommon.c
dir ..\..\py\emitbc.c
dir ..\..\py\asmbase.c
dir ..\..\py\asmx64.c
dir ..\..\py\emitnx64.c
dir ..\..\py\asmx86.c
dir ..\..\py\emitnx86.c
dir ..\..\py\asmthumb.c
dir ..\..\py\emitnthumb.c
dir ..\..\py\emitinlinethumb.c
dir ..\..\py\asmarm.c
dir ..\..\py\emitnarm.c
dir ..\..\py\asmxtensa.c
dir ..\..\py\emitnxtensa.c
dir ..\..\py\emitinlinextensa.c
dir ..\..\py\emitnxtensawin.c
dir ..\..\py\formatfloat.c
dir ..\..\py\parsenumbase.c
dir ..\..\py\parsenum.c
dir ..\..\py\emitglue.c
dir ..\..\py\persistentcode.c
dir ..\..\py\runtime.c
dir ..\..\py\runtime_utils.c
dir ..\..\py\scheduler.c
dir ..\..\py\nativeglue.c
dir ..\..\py\pairheap.c
dir ..\..\py\ringbuf.c
dir ..\..\py\stackctrl.c
dir ..\..\py\argcheck.c
dir ..\..\py\warning.c
dir ..\..\py\profile.c
dir ..\..\py\map.c
dir ..\..\py\obj.c
dir ..\..\py\objarray.c
dir ..\..\py\objattrtuple.c
dir ..\..\py\objbool.c
dir ..\..\py\objboundmeth.c
dir ..\..\py\objcell.c
dir ..\..\py\objclosure.c
dir ..\..\py\objcomplex.c
dir ..\..\py\objdeque.c
dir ..\..\py\objdict.c
dir ..\..\py\objenumerate.c
dir ..\..\py\objexcept.c
dir ..\..\py\objfilter.c
dir ..\..\py\objfloat.c
dir ..\..\py\objfun.c
dir ..\..\py\objgenerator.c
dir ..\..\py\objgetitemiter.c
dir ..\..\py\objint.c
dir ..\..\py\objint_longlong.c
dir ..\..\py\objint_mpz.c
dir ..\..\py\objlist.c
dir ..\..\py\objmap.c
dir ..\..\py\objmodule.c
dir ..\..\py\objobject.c
dir ..\..\py\objpolyiter.c
dir ..\..\py\objproperty.c
dir ..\..\py\objnone.c
dir ..\..\py\objnamedtuple.c
dir ..\..\py\objrange.c
dir ..\..\py\objreversed.c
dir ..\..\py\objset.c
dir ..\..\py\objsingleton.c
dir ..\..\py\objslice.c
dir ..\..\py\objstr.c
dir ..\..\py\objstrunicode.c
dir ..\..\py\objstringio.c
dir ..\..\py\objtuple.c
dir ..\..\py\objtype.c
dir ..\..\py\objzip.c
dir ..\..\py\opmethods.c
dir ..\..\py\sequence.c
dir ..\..\py\stream.c
dir ..\..\py\binary.c
dir ..\..\py\builtinimport.c
dir ..\..\py\builtinevex.c
dir ..\..\py\builtinhelp.c
dir ..\..\py\modarray.c
dir ..\..\py\modbuiltins.c
dir ..\..\py\modcollections.c
dir ..\..\py\modgc.c
dir ..\..\py\modio.c
dir ..\..\py\modmath.c
dir ..\..\py\modcmath.c
dir ..\..\py\modmicropython.c
dir ..\..\py\modstruct.c
dir ..\..\py\modsys.c
dir ..\..\py\moduerrno.c
dir ..\..\py\modthread.c
dir ..\..\py\vm.c
dir ..\..\py\bc.c
dir ..\..\py\showbc.c
dir ..\..\py\repl.c
dir ..\..\py\smallint.c
dir ..\..\py\frozenmod.c
dir ..\..\extmod\machine_bitstream.c
dir ..\..\extmod\machine_i2c.c
dir ..\..\extmod\machine_mem.c
dir ..\..\extmod\machine_pinbase.c
dir ..\..\extmod\machine_pulse.c
dir ..\..\extmod\machine_pwm.c
dir ..\..\extmod\machine_signal.c
dir ..\..\extmod\machine_spi.c
dir ..\..\extmod\machine_timer.c
dir ..\..\extmod\modbluetooth.c
dir ..\..\extmod\modbtree.c
dir ..\..\extmod\modframebuf.c
dir ..\..\extmod\modlwip.c
dir ..\..\extmod\modnetwork.c
dir ..\..\extmod\modonewire.c
dir ..\..\extmod\moduasyncio.c
dir ..\..\extmod\modubinascii.c
dir ..\..\extmod\moducryptolib.c
dir ..\..\extmod\moductypes.c
dir ..\..\extmod\moduhashlib.c
dir ..\..\extmod\moduheapq.c
dir ..\..\extmod\modujson.c
dir ..\..\extmod\moduos.c
dir ..\..\extmod\moduplatform.c
dir ..\..\extmod\modurandom.c
dir ..\..\extmod\modure.c
dir ..\..\extmod\moduselect.c
dir ..\..\extmod\modusocket.c
dir ..\..\extmod\modussl_axtls.c
dir ..\..\extmod\modussl_mbedtls.c
dir ..\..\extmod\modutimeq.c
dir ..\..\extmod\moduwebsocket.c
dir ..\..\extmod\moduzlib.c
dir ..\..\extmod\modwebrepl.c
dir ..\..\extmod\network_cyw43.c
dir ..\..\extmod\network_ninaw10.c
dir ..\..\extmod\network_wiznet5k.c
dir ..\..\extmod\uos_dupterm.c
dir ..\..\extmod\utime_mphal.c
dir ..\..\extmod\vfs.c
dir ..\..\extmod\vfs_blockdev.c
dir ..\..\extmod\vfs_fat.c
dir ..\..\extmod\vfs_fat_diskio.c
dir ..\..\extmod\vfs_fat_file.c
dir ..\..\extmod\vfs_lfs.c
dir ..\..\extmod\vfs_posix.c
dir ..\..\extmod\vfs_posix_file.c
dir ..\..\extmod\vfs_reader.c
dir ..\..\extmod\virtpin.c
dir ..\..\shared\libc\abort_.c
dir ..\..\shared\libc\printf.c
dir boardctrl.c
dir main.c
dir mphalport.c
dir mpnetworkport.c
dir mpthreadport.c
dir irq.c
dir pendsv.c
dir systick.c
dir factoryreset.c
dir led.c
dir pin.c
dir pin_defs_rz.c
dir pin_named_pins.c
dir bufhelper.c
dir i2c.c
dir pyb_i2c.c
dir spi.c
dir pyb_spi.c
dir uart.c
dir eth.c
dir gccollect.c
dir help.c
dir machine_i2c.c
dir machine_spi.c
dir machine_timer.c
dir machine_uart.c
dir modmachine.c
dir modpyb.c
dir modrz.c
dir modutime.c
dir network_lan.c
dir extint.c
dir usrsw.c
dir rng.c
dir rtc.c
dir flash.c
dir flashbdev.c
dir storage.c
dir sdcard.c
dir fatfs_port.c
dir lcd.c
dir servo.c
dir adc.c
dir modrzreg.c
dir mpy_file.c
dir phy.c
dir pwm.c
dir softtimer.c
dir rz_buf.c
dir display.c
dir rz_camera.c
dir rz_display.c
dir rz_lcd.c
dir rz_drp.c
dir rz_isp.c
dir ..\..\extmod\network_esp.c
dir rz_font.c
dir rz_lcdspi.c
dir ..\..\shared\libc\string0.c
dir ..\..\shared\netutils\dhcpserver.c
dir ..\..\shared\netutils\netutils.c
dir ..\..\shared\netutils\trace.c
dir ..\..\shared\readline\readline.c
dir ..\..\shared\runtime\gchelper_native.c
dir ..\..\shared\runtime\interrupt_char.c
dir ..\..\shared\runtime\mpirq.c
dir ..\..\shared\runtime\pyexec.c
dir ..\..\shared\runtime\stdout_helpers.c
dir ..\..\shared\runtime\sys_stdio_mphal.c
dir ..\..\shared\timeutils\timeutils.c
dir mpconfigboard_common.h
dir boards\GR_MANGO\mpconfigboard.h
dir build-GR_MANGO\pins_qstr.h
dir ..\..\py\mpconfig.h
dir mpconfigport.h
dir dependencies
dir mpconfigboard_common.h
dir boards\GR_MANGO\mpconfigboard.h
dir build-GR_MANGO\pins_qstr.h
dir ..\..\py\mpconfig.h
dir mpconfigport.h
dir changed_sources
dir ..\..\py\mpstate.c
dir ..\..\py\malloc.c
dir ..\..\py\gc.c
dir ..\..\py\pystack.c
dir ..\..\py\qstr.c
dir ..\..\py\vstr.c
dir ..\..\py\mpprint.c
dir ..\..\py\unicode.c
dir ..\..\py\mpz.c
dir ..\..\py\reader.c
dir ..\..\py\lexer.c
dir ..\..\py\parse.c
dir ..\..\py\scope.c
dir ..\..\py\compile.c
dir ..\..\py\emitcommon.c
dir ..\..\py\emitbc.c
dir ..\..\py\asmbase.c
dir ..\..\py\asmx64.c
dir ..\..\py\emitnx64.c
dir ..\..\py\asmx86.c
dir ..\..\py\emitnx86.c
dir ..\..\py\asmthumb.c
dir ..\..\py\emitnthumb.c
dir ..\..\py\emitinlinethumb.c
dir ..\..\py\asmarm.c
dir ..\..\py\emitnarm.c
dir ..\..\py\asmxtensa.c
dir ..\..\py\emitnxtensa.c
dir ..\..\py\emitinlinextensa.c
dir ..\..\py\emitnxtensawin.c
dir ..\..\py\formatfloat.c
dir ..\..\py\parsenumbase.c
dir ..\..\py\parsenum.c
dir ..\..\py\emitglue.c
dir ..\..\py\persistentcode.c
dir ..\..\py\runtime.c
dir ..\..\py\runtime_utils.c
dir ..\..\py\scheduler.c
dir ..\..\py\nativeglue.c
dir ..\..\py\pairheap.c
dir ..\..\py\ringbuf.c
dir ..\..\py\stackctrl.c
dir ..\..\py\argcheck.c
dir ..\..\py\warning.c
dir ..\..\py\profile.c
dir ..\..\py\map.c
dir ..\..\py\obj.c
dir ..\..\py\objarray.c
dir ..\..\py\objattrtuple.c
dir ..\..\py\objbool.c
dir ..\..\py\objboundmeth.c
dir ..\..\py\objcell.c
dir ..\..\py\objclosure.c
dir ..\..\py\objcomplex.c
dir ..\..\py\objdeque.c
dir ..\..\py\objdict.c
dir ..\..\py\objenumerate.c
dir ..\..\py\objexcept.c
dir ..\..\py\objfilter.c
dir ..\..\py\objfloat.c
dir ..\..\py\objfun.c
dir ..\..\py\objgenerator.c
dir ..\..\py\objgetitemiter.c
dir ..\..\py\objint.c
dir ..\..\py\objint_longlong.c
dir ..\..\py\objint_mpz.c
dir ..\..\py\objlist.c
dir ..\..\py\objmap.c
dir ..\..\py\objmodule.c
dir ..\..\py\objobject.c
dir ..\..\py\objpolyiter.c
dir ..\..\py\objproperty.c
dir ..\..\py\objnone.c
dir ..\..\py\objnamedtuple.c
dir ..\..\py\objrange.c
dir ..\..\py\objreversed.c
dir ..\..\py\objset.c
dir ..\..\py\objsingleton.c
dir ..\..\py\objslice.c
dir ..\..\py\objstr.c
dir ..\..\py\objstrunicode.c
dir ..\..\py\objstringio.c
dir ..\..\py\objtuple.c
dir ..\..\py\objtype.c
dir ..\..\py\objzip.c
dir ..\..\py\opmethods.c
dir ..\..\py\sequence.c
dir ..\..\py\stream.c
dir ..\..\py\binary.c
dir ..\..\py\builtinimport.c
dir ..\..\py\builtinevex.c
dir ..\..\py\builtinhelp.c
dir ..\..\py\modarray.c
dir ..\..\py\modbuiltins.c
dir ..\..\py\modcollections.c
dir ..\..\py\modgc.c
dir ..\..\py\modio.c
dir ..\..\py\modmath.c
dir ..\..\py\modcmath.c
dir ..\..\py\modmicropython.c
dir ..\..\py\modstruct.c
dir ..\..\py\modsys.c
dir ..\..\py\moduerrno.c
dir ..\..\py\modthread.c
dir ..\..\py\vm.c
dir ..\..\py\bc.c
dir ..\..\py\showbc.c
dir ..\..\py\repl.c
dir ..\..\py\smallint.c
dir ..\..\py\frozenmod.c
dir ..\..\extmod\machine_bitstream.c
dir ..\..\extmod\machine_i2c.c
dir ..\..\extmod\machine_mem.c
dir ..\..\extmod\machine_pinbase.c
dir ..\..\extmod\machine_pulse.c
dir ..\..\extmod\machine_pwm.c
dir ..\..\extmod\machine_signal.c
dir ..\..\extmod\machine_spi.c
dir ..\..\extmod\machine_timer.c
dir ..\..\extmod\modbluetooth.c
dir ..\..\extmod\modbtree.c
dir ..\..\extmod\modframebuf.c
dir ..\..\extmod\modlwip.c
dir ..\..\extmod\modnetwork.c
dir ..\..\extmod\modonewire.c
dir ..\..\extmod\moduasyncio.c
dir ..\..\extmod\modubinascii.c
dir ..\..\extmod\moducryptolib.c
dir ..\..\extmod\moductypes.c
dir ..\..\extmod\moduhashlib.c
dir ..\..\extmod\moduheapq.c
dir ..\..\extmod\modujson.c
dir ..\..\extmod\moduos.c
dir ..\..\extmod\moduplatform.c
dir ..\..\extmod\modurandom.c
dir ..\..\extmod\modure.c
dir ..\..\extmod\moduselect.c
dir ..\..\extmod\modusocket.c
dir ..\..\extmod\modussl_axtls.c
dir ..\..\extmod\modussl_mbedtls.c
dir ..\..\extmod\modutimeq.c
dir ..\..\extmod\moduwebsocket.c
dir ..\..\extmod\moduzlib.c
dir ..\..\extmod\modwebrepl.c
dir ..\..\extmod\network_cyw43.c
dir ..\..\extmod\network_ninaw10.c
dir ..\..\extmod\network_wiznet5k.c
dir ..\..\extmod\uos_dupterm.c
dir ..\..\extmod\utime_mphal.c
dir ..\..\extmod\vfs.c
dir ..\..\extmod\vfs_blockdev.c
dir ..\..\extmod\vfs_fat.c
dir ..\..\extmod\vfs_fat_diskio.c
dir ..\..\extmod\vfs_fat_file.c
dir ..\..\extmod\vfs_lfs.c
dir ..\..\extmod\vfs_posix.c
dir ..\..\extmod\vfs_posix_file.c
dir ..\..\extmod\vfs_reader.c
dir ..\..\extmod\virtpin.c
dir ..\..\shared\libc\abort_.c
dir ..\..\shared\libc\printf.c
dir boardctrl.c
dir main.c
dir mphalport.c
dir mpnetworkport.c
dir mpthreadport.c
dir irq.c
dir pendsv.c
dir systick.c
dir factoryreset.c
dir led.c
dir pin.c
dir pin_defs_rz.c
dir pin_named_pins.c
dir bufhelper.c
dir i2c.c
dir pyb_i2c.c
dir spi.c
dir pyb_spi.c
dir uart.c
dir eth.c
dir gccollect.c
dir help.c
dir machine_i2c.c
dir machine_spi.c
dir machine_timer.c
dir machine_uart.c
dir modmachine.c
dir modpyb.c
dir modrz.c
dir modutime.c
dir network_lan.c
dir extint.c
dir usrsw.c
dir rng.c
dir rtc.c
dir flash.c
dir flashbdev.c
dir storage.c
dir sdcard.c
dir fatfs_port.c
dir lcd.c
dir servo.c
dir adc.c
dir modrzreg.c
dir mpy_file.c
dir phy.c
dir pwm.c
dir softtimer.c
dir rz_buf.c
dir display.c
dir rz_camera.c
dir rz_display.c
dir rz_lcd.c
dir rz_drp.c
dir rz_isp.c
dir ..\..\extmod\network_esp.c
dir rz_font.c
dir rz_lcdspi.c
dir ..\..\shared\libc\string0.c
dir ..\..\shared\netutils\dhcpserver.c
dir ..\..\shared\netutils\netutils.c
dir ..\..\shared\netutils\trace.c
dir ..\..\shared\readline\readline.c
dir ..\..\shared\runtime\gchelper_native.c
dir ..\..\shared\runtime\interrupt_char.c
dir ..\..\shared\runtime\mpirq.c
dir ..\..\shared\runtime\pyexec.c
dir ..\..\shared\runtime\stdout_helpers.c
dir ..\..\shared\runtime\sys_stdio_mphal.c
dir ..\..\shared\timeutils\timeutils.c
dir mpconfigboard_common.h
dir boards\GR_MANGO\mpconfigboard.h
dir build-GR_MANGO\pins_qstr.h
dir ..\..\py\mpconfig.h
dir mpconfigport.h
dir 