MCU_SERIES = RX63N
MCU_NUMBER = R5F563NBDDFP
LD_FILES = boards/GR_SAKURA/gr_sakura.ld
START_FILE = rx63n/startup_rx63n.S

# MicroPython settings
MICROPY_VFS_FAT = 1
MICROPY_PY_LWIP=1
MICROPY_PY_USSL=1
MICROPY_SSL_MBEDTLS=1
