name: rx port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/rx/**'

jobs:
  build_gr_rose:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: source tools/ci.sh && ci_rx_setup
    - name: Build mpy-cross
      run: source tools/ci.sh && ci_rx_mpy_cross_build
    - name: Build
      run: source tools/ci.sh && ci_rx_gr_rose_build

